version: '3'

services:
  frontend:
    build:
      context: frontend
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '64M'
    volumes:
      - './configs/frontend:/etc/nginx/ssl'
    ports:
      - '443:443'
    depends_on:
      - gateway
    networks:
      - frontend2core
      - frontend2gateway
